version: 2
jobs:
  build:
    docker:
      - image: fedora:26
        environment:
          GOPATH: /root/golang
    working_directory: ~/resume
    steps:
      - run: dnf install -y git make golang texlive-latex-bin texlive-scheme-basic texlive-titlesec texlive-blindtext texlive-caladea texlive-ec
      - checkout
      - run: make
      - run: go get github.com/aktau/github-release
      - store_artifacts:
          path: _build/resume.pdf
      - deploy:
          command: |
            $GOPATH/bin/github-release release \
              --user sbaildon \
              --repo resume \
              --tag `date +%Y-%m-%d_%H-%M`
            $GOPATH/bin/github-release upload \
              --user sbaildon \
              --repo resume \
              --tag `date +%Y-%m-%d_%H-%M` \
              --name resume.pdf \
              --file _build/resume.pdf
