version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/
    steps:
      - run: apt-get update -y
      - run: apt-get install -y make texlive-latex-base texlive-fonts-extra
      - run: cd resume; make
