version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    working_directory: ~/resume
    steps:
      - run: apt-get update -y
      - run: apt-get install -y git make texlive-latex-base texlive-fonts-extra
      - checkout
      - run: make
      - store_artifacts:
          path: _build/resume.pdf
