version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
        environment:
          GOPATH: ~/golang
    working_directory: ~/resume
    steps:
      - run: apt-get update -y
      - run: apt-get install -y git make golang texlive-latex-base texlive-fonts-extra
      - checkout
      - run: make
      - run: go get github-release
      - store_artifacts:
          path: _build/resume.pdf
